### ISSUE TITLE
Coffee image in not showing in tab of cofee

### ISSUE THREAD

**Issue by vipinkesari** [hani-momanii/SuperNova-Emoji#3]
Instead of showing coffee image, it is showing the unicode. unicode is displayed in coffee section , before the mile bottle.

**Comment by hani-momanii** [comment]
Will fixed in the next update

**Comment by rahulr4** [comment]
The fix for this is :-
In Food.Java , do this :-

Emojicon.fromChar((char) 0x2615), // Add this line
/*Emojicon.fromCodePoint(0x2615),*/ // Comment this line

**Comment by afaideen** [comment]
Would you please update the dependency here so that user can just pull
compile 'hani.momanii.supernova_emoji_library:supernova-emoji-library:0.0.2'

**Comment by afaideen** [comment]
Hello sir i think your dependency still not updated. Would you please?

**Comment by rahulr4** [comment]
This is not my source code and i cannot update the jcenter dependency version.
However, to fix it, you just need to modify one line of code : -
Open Food.Java
Find this line of code `Emojicon.fromCodePoint(0x2615)`
It must be on line number 70
Change it to `Emojicon.fromChar((char) 0x2615)`
There , you are good to go now.

**Comment by rahulr4** [comment]
Also, request the repository owner to update library with new emoji's as we have new emoji's in ios

**Comment by hani-momanii** [comment]
You can find the fix in V 1.1
```
repositories {
    maven { url 'https://jitpack.io' }
}
compile 'com.github.hani-momanii:SuperNova-Emoji:1.1'
```

**Comment by afaideen** [comment]
thx hani momani. it now resolve my problem.
